version: "3"

services:
  list-partition:
    image: postgres:14.2-alpine
    container_name: range-partition
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: range-partition
    volumes:
      - ./dbinit:/docker-entrypoint-initdb.d
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432