version: '3'
services:
  db:
    image: mysql:8
    container_name: mysql
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: wpsota08
      MYSQL_DATABASE: wpdb
      MYSQL_USER: user
      MYSQL_PASSWORD: wpsota08
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - wordpress
  wordpress:
    depends_on:
      - db
    restart: unless-stopped
    image: wordpress
    container_name: wordpress
    volumes:
      - ./wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wpdb
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: wpsota08
    ports:
      - 8080:80
    networks:
      - wordpress
  phpmyadmin:
    depends_on:
      - db
    restart: unless-stopped
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 3333:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORT: wpsota08
    networks:
      - wordpress
  nginx:
    container_name: nginx
    image: nginx:1.21.6-alpine
    tty: true
    stdin_open: true
    volumes:
      - ./config:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8082:80"
    networks:
      - wordpress
networks:
  wordpress:
    driver: bridge