version: "3"

services:
  postgres-index:
    image: postgres:14.2-alpine
    container_name: postgres-index
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: index-gres
    volumes:
      - ./dbinit:/docker-entrypoint-initdb.d
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432