version: "3"

services:
  sam-container:
    build:
      context: .
      target: base
    container_name: sam-container
    tty: true
    stdin_open: true
    volumes:
      - ./src:/var/opt:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - sam-container
    ports:
      - "25:3000"
networks:
  sam-container: