FROM alpine:3.15.4 as base

ENV VERSION=1.46.0

RUN apk add --no-cache curl && \
    curl -sSLO https://github.com/aws/aws-sam-cli/releases/download/v${VERSION}/aws-sam-cli-${VERSION}.x86_64_linux.bottle.tar.gz && \
    tar -C /usr/local/bin -zxvf /aws-sam-cli-${VERSION}.x86_64_linux.bottle.tar.gz && \
    apk del curl && \
    rm -f /aws-sam-cli-${VERSION}.x86_64_linux.bottle.tar.gz

# awscli for "sam package" and "sam deploy"
RUN apk add --no-cache py-pip && pip install awscli

WORKDIR /var/opt

ENTRYPOINT ["chmod", "+x", "/usr/local/bin/aws-sam-cli"]